// <auto-generated />
namespace AplicacionWebColegio.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HerenciaPersona : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HerenciaPersona));
        
        string IMigrationMetadata.Id
        {
            get { return "201612180444447_HerenciaPersona"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
